server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/odour?characterEncoding=utf-8&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

localImgPath: C:/Users/li/Desktop/nginx/resource/
networkImgPath: resource/
rawFileDir: C:/Users/li/Desktop/nginx/resource/download/
teamNewsDir: C:/Users/li/Desktop/nginx/resource/static/news/